### ISSUE TITLE
Support for the notification server

### ISSUE THREAD

**Issue by FluffyDiscord** [ggogel/seafile-containerized#104]
v10 introduces new notification server that should reduce the load by replacing pull/push behavior by websockets, would it be possible to add it in? https://manual.seafile.com/deploy/notification-server/

**Comment by ggogel** [comment]
Hi, thanks for the feature request. I honestly didn't even know that the notification server requires configuration.

I just released new versions that support the notification server.

I have to note one thing: The `[notification]` config section was already created automatically by Seafile, including the `jwt_private_key`. Though, using this pre-created key caused HTTP Error 400 on requests to the notification server. If this is also the case for you, make sure to generate your own key with `openssl rand -base64 32`.

To activate follow the steps in the linked documentation and then restart the sefile-server container.

**Comment by ggogel** [comment]
Implemented in 57b983d3e6c94a39766d2779427d0a95a4ed1fb9 and d9925fda7dcf811ef15d3e40f72dd9882a76e8a2
