### ISSUE TITLE
`gc_cron` in `start.sh` runs on every `docker compose restart`

### ISSUE THREAD

**Issue by wangzexi** [ggogel/seafile-containerized#106]
![](https://github.com/ggogel/seafile-containerized/assets/13242100/dcf1d0cb-343d-4168-92c3-7af97b59ad23)

https://github.com/ggogel/seafile-containerized/blob/45a585d945235d958385c2a433e95c971b150bfc/seafile-server/Dockerfile#L56

https://github.com/ggogel/seafile-containerized/blob/45a585d945235d958385c2a433e95c971b150bfc/seafile-server/scripts/start.sh#L6

---

So, when the `gc.sh` in the `crontab` ends, it seems to trigger the seafile-server to start multiple times, and then the port binding problem occurs.

https://github.com/ggogel/seafile-containerized/blob/45a585d945235d958385c2a433e95c971b150bfc/seafile-server/scripts/gc.sh#L22

**Comment by ggogel** [comment]
Thanks for the issue report. I never noticed it because Docker Swarm creates a new container on restart.

Fixed in ff1c91c
