### ISSUE TITLE
Support for Kubernetes (K8s)

### ISSUE THREAD

**Issue by zlinuxboy** [ggogel/seafile-containerized#114]

**Comment by ggogel** [comment]
In theory, it is possible. I just did not have the time to create Kubernetes manifests or Helm Charts yet. PR appreciated.

**Comment by alpharde** [comment]
`Note: We expect certain services names. Do not rename services except db.`

Are service names hardcoded? Kubernetes has it's own way of dealing with services so this needs to be configurable.

**Comment by ggogel** [comment]
> `Note: We expect certain services names. Do not rename services except db.`
> 
> Are service names hardcoded? Kubernetes has it's own way of dealing with services so this needs to be configurable.

Service names are not hardcoded anymore. This information is out of date.

See https://github.com/ggogel/seafile-containerized/blob/fb9e2a4a7ebebce2aba4bacdcaba29c72e979c90/seafile-caddy/Dockerfile#L11-L13

**Comment by ggogel** [comment]
I've just added Kubernetes manifests to the project. See https://github.com/ggogel/seafile-containerized/wiki/Kubernetes for installation instructions.

I also plan to add a Helm chart with templating logic in the future for easier configuration.
