### ISSUE TITLE
Emails fail to send due to DNS issue

### ISSUE THREAD

**Issue by yeah-mike** [ggogel/seafile-containerized#12]
Seafile can be configured to send out emails for things such as password resets or new user registration. Setup is described here: https://manual.seafile.com/config/sending_email/

My email settings are configured correctly, but the emails fail to send and return with `Errno-3`. Google suggests `Errno-3` thrown by django is due to a DNS name resolution problem. Indeed, if I add the `default` network to either `seahub` or `seafile-server` (sorry I can't remember which one; I currently have it added to both while I'm troubleshooting some other issues) then the emails will send successfully.

**Comment by ggogel** [comment]
It fails because *seafile-net* is declared as internal: https://github.com/ggogel/seafile-containerized/blob/367cfcfd85de7d6f8745c10c1af755be1848854b/compose/docker-compose.yml#L73-L75

The services connected to this network can only communicate with each other and not with any external endpoints.
