### ISSUE TITLE
waiting for mysql server to be ready: %s (2003, "Can't connect to MySQL server on 'db' (timed out)")

### ISSUE THREAD

**Issue by hinink** [ggogel/seafile-containerized#152]
waiting for mysql server to be ready: %s (2003, "Can't connect to MySQL server on 'db' (timed out)")

**Comment by hinink** [comment]
version: '3.8'
services:
  seafile-server:
    image: ggogel/seafile-server:8.0.2
    volumes:
      - seafile-data:/shared 
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=db_dev
      - TIME_ZONE=Europe/Berlin
      - SEAFILE_ADMIN_EMAIL=seafile@izsw.net
      - SEAFILE_ADMIN_PASSWORD=123456
      - HTTPS=false # Set this to true if you plan to use a reverse proxy with HTTPS. Can be changed later in the admin settings on the web-ui.
      - SEAFILE_SERVER_HOSTNAME=192.168.58.243 # Mandatory on first deployment!
    depends_on:
      - db
      - memcached
      - seafile-caddy
    networks:
      - seafile-net

  seahub:
    image: ggogel/seahub:8.0.2
    volumes:
      - seafile-data:/shared
      - seahub-avatars:/shared/seafile/seahub-data/avatars
      - seahub-custom:/shared/seafile/seahub-data/custom 
    depends_on:
      - seafile-server
      - seafile-caddy
    networks:
      - seafile-net
  
  seahub-media:
    image: ggogel/seahub-media:8.0.2
    volumes:
     - seahub-avatars:/usr/share/caddy/media/avatars
     - seahub-custom:/usr/share/caddy/media/custom
    depends_on:
      - seafile-server
      - db
      - memcached
      - seafile-caddy
    networks:
      - seafile-net

  db:
    image: mariadb:10.5.8
    environment:
      - MYSQL_ROOT_PASSWORD=db_dev
      - MYSQL_LOG_CONSOLE=true
    hostname: db
    volumes:
      - seafile-mariadb:/var/lib/mysql
    networks:
      - seafile-net

  memcached:
    image: memcached:1.6.9
    entrypoint: memcached -m 1024
    networks:
      - seafile-net

  seafile-caddy:
    image: ggogel/seafile-caddy:1.0.0
    ports:
      - 80:80 # Point your reverse proxy to port 80 of this service
    networks:
      - seafile-net

networks:
  seafile-net:
    internal: true

volumes:
  seafile-data:
  seafile-mariadb:
  seahub-avatars:
  seahub-custom:

**Comment by ggogel** [comment]
Sorry but posting an error message and a compose file isn't an issue report.
