### ISSUE TITLE
Support for FUSE extension

### ISSUE THREAD

**Issue by adinklotz** [ggogel/seafile-containerized#156]
Hi,
Seafile supports a [FUSE extension](https://manual.seafile.com/extension/fuse/) for browsing the server as if it were a normal filesystem. It looks like it is possible to trigger this from within Docker, but it requires manually starting it up from a container shell. It would be great if the image could be configured to automatically start the FUSE process and attach it to a bind-mounted directory.

**Comment by ggogel** [comment]
Hi,

What exactly would be a use case for this?

The documentation states that the file mount can only be accessed read only.

Further, to mount a volume inside a container, the container needs system administrator capabilities, as demonstrated in the docs. This is quite a security risk.

You can always modify the Dockerfile or CMD in compose to modify the container. I'm sorry but this looks like something I'm not going to support.

**Comment by max-critcrew** [comment]
@ggogel The main use-case would be to have automatic backups that are independant of Seafile's way of storing files and be able to later on restore the backup to a fully new Seafile install if anything goes terribly wrong.

**Comment by ggogel** [comment]
Rclone has a seafile backend, which uses the seafdav (webdav) interface of seafile: https://rclone.org/seafile/

Or you can use any other webdav client.

**Comment by max-critcrew** [comment]
@ggogel Thanks! Are you using rclone for backups currently? Any other suggestion how you'd handle it? Thanks again and also thanks for this project! :)

**Comment by ggogel** [comment]
I'm not doing any backups on file level at the moment. Since I synced my libraries across several devices, I don't think that this is necessary.

I'm taking snapshots and backups at volume level with Longhorn. I'm using Longhorn as storage solution for Kubernetes. Before migrating to Kubernetes, I used Veeam to take backups of my virtual machines running Docker.
