### ISSUE TITLE
Seafile doesn't come up after rebuilding the images today

### ISSUE THREAD

**Issue by hnz101** [ggogel/seafile-containerized#159]
Hi,
I rebuild my images today and after that it seems like seahub isn't coming up.
(I build the images myself, with this repo here and don't use the docker hub images.)

Caddy gets timeout requesting 172.25.0.6:8000 and 172.25.0.5:8082. So seahub and seafhttp? are not up.
The only curios thing I can really see in the logs is: seahub_1  | Error happened during creating seafile admin.

Perhaps some Python dependency got updated and broke something?
Can someone confirm the same behavior?

**Comment by ggogel** [comment]
Hi,

Unfortunately, I can't reproduce your issue. All services are working for me on the latest release.

The error `Error happened during creating seafile admin` can be ignored.

Try to run docker-compose with `--force-recreate`.

If this doesn't help, please post your full logs. Also, could you specify what you mean by rebuilding the images?

**Comment by hnz101** [comment]
I found my problem. I ran into an Docker+firewalld Bug which broke internal network communication between docker containers. (https://github.com/moby/libnetwork/issues/2647).
I have no idea why this showed today, I use this setup since a long time. Perhaps it emerged with an docker-ce update this week.

Thank You for your fast answer!
