### ISSUE TITLE
Emails are not being send

### ISSUE THREAD

**Issue by faethon** [ggogel/seafile-containerized#211]
I seems to be having a problem with sending emails. I have added the config to seahub_settings.py conform the instructions from Seafile:
(Using a app password from Gmail.)

```
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'email@email.com'
EMAIL_HOST_PASSWORD = 'app_password'
EMAIL_PORT = 587
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER
```

Whenever an email needs to be send I get a notification that says 

`"Successfully reset password to ------, but failed to send email to 5fde94bf------------------5697af@auth.local, please check your email configuration."`

I am running the latest ggogel/seafile-containerized docker file with seafile 11.0.6.

As per issue [5933](https://github.com/haiwen/seahub/issues/5933) I have tried to add the following to the environment of the seahub container, but this does not seem to solve anything. 

`SSL_CERT_FILE=/etc/ssl/certs/cabundle.pem`

Furthermore, that pem file is not available at that location within the container: 

Looking in seahub.log I see this error popping up when trying to send an email:
`[WARNING] seahub.api2.endpoints.admin.users:1508 put [Errno -3] Try again`

**Comment by ggogel** [comment]
Is your seahub container only in the internal network `seafile-net`? Then it won't be able to reach `gmail.com`. Refer to this wiki article with the similar situation when using LDAP https://github.com/ggogel/seafile-containerized/wiki/LDAP

**Comment by faethon** [comment]
Thanks so much. That was indeed the problem. The stack was not accessing outside.
