### ISSUE TITLE
seafile not coming up after upgrade from 11.0.2 to 11.0.8

### ISSUE THREAD

**Issue by coro1404** [ggogel/seafile-containerized#233]
Upgraded docker-compose from 11.0.2 to 11.0.8 today and seafile won't come up (works if downgrading to 11.0.2 again). Only error in error Log is: 

seafile-caddy-1   | {"level":"error","ts":1715427215.1893396,"logger":"http.log.error","msg":"dial tcp: lookup seahub on 127.0.0.11:53: server misbehaving","request":{"remote_ip":"172.19.0.9","remote_port":"37570","client_ip":"172.19.0.9","proto":"HTTP/1.1","method":"GET","host":"seafile.kendoo.eu","uri":"/","headers":{"Cookie":[],"Sec-Ch-Ua-Mobile":["?0"],"User-Agent":["Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"],"Accept-Language":["de-DE,de;q=0.9,en-GB;q=0.8,en;q=0.7,en-US;q=0.6"],"Sec-Fetch-Dest":["document"],"Sec-Fetch-Site":["none"],"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"],"Accept-Encoding":["gzip, deflate, br, zstd"],"Sec-Ch-Ua":["\"Google Chrome\";v=\"123\", \"Not:A-Brand\";v=\"8\", \"Chromium\";v=\"123\""],"X-Forwarded-Host":["seafile.kendoo.eu"],"Sec-Ch-Ua-Platform":["\"Chrome OS\""],"Upgrade-Insecure-Requests":["1"],"X-Forwarded-For":["87.132.14.213"],"Sec-Fetch-Mode":["navigate"],"Sec-Fetch-User":["?1"],"X-Forwarded-Proto":["https"]}},"duration":0.002633181,"status":502,"err_id":"j1kbbgb57","err_trace":"reverseproxy.statusError (reverseproxy.go:1267)"}

can provide full log if necessary

**Comment by ggogel** [comment]
Hi, the provided error just means that caddy can't get through to the seahub container. So either the container or the service inside isn't running. Maybe try to upgrade version by version. If you still face an issue, please provide a full log.

**Comment by coro1404** [comment]
you were right - this was due to an error by me - upgrading without the versions in between an minor tweaks of the docker compose fixed the issue. Thanks for replying - issue can be closed.
