### ISSUE TITLE
seahub container without internet access

### ISSUE THREAD

**Issue by coro1404** [ggogel/seafile-containerized#234]
Might be problem of my setup - but tried to setup SSO with keycloak which failed with the seahub container logging: 

> seahub-1          | 2024-05-11 23:26:27,633 [ERROR] seahub.oauth.views:154 oauth_callback HTTPSConnectionPool(host='keycloak.xx.yy', port=443): Max retries exceeded with url: /realms/kendoo/protocol/openid-connect/token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f6660647af0>: Failed to resolve 'keycloak.xx.yy' ([Errno -3] Try again)"))
seahub-1          | 2024-05-11 23:26:28,074 [INFO] xmlschema:1234 include_schema Resource 'XMLSchema.xsd' is already loaded

entering the container shows no internet access / dns resolution 

> e3a3b4aa0af2:/# ping keycloak.xx.yy
ping: bad address 'keycloak.xx.yy'

I changed docker-compose.yaml for seahub container to contain also network default - after that ping works and SSO works. Suggesting seahub container should also have default network (but might me my setup) . By the way many changes for SSO between version 10 and 11 so make sure to use most up 2 date documentation.

**Comment by ggogel** [comment]
The network is by design declared as internal. See #211 and https://github.com/ggogel/seafile-containerized/wiki/OAuth for reference.
