### ISSUE TITLE
Option to specify seafile-memcached hostname

### ISSUE THREAD

**Issue by kanpov** [ggogel/seafile-containerized#250]
Currently I hit a roadblock when running this inside Podman Quadlets with a pod, a Podman pod has internal services listening on `0.0.0.0`. However, it seems that the `seahub` image has no way to change the hostname for memcached and it's just hardcoded to `memcached`, which is problematic.

**Comment by ggogel** [comment]
The memcached hostname and port are written into `seahub_settings.py` during bootstrapping:
https://github.com/ggogel/seafile-containerized/blob/8a917892e69b6433ba37b5e56d6ee76ccf1e3c90/seafile-server/scripts/bootstrap.py#L81-L91

If you want to change the hostname, you can edit `seahub_settings.py` after bootstrapping.
