### ISSUE TITLE
Seafile doesn't start because seafile server can't comunicate to database

### ISSUE THREAD

**Issue by Laikar** [ggogel/seafile-containerized#274]
Running my deployment in a test vm because I as adding a new service, seafile refused to start .
I tried the provided docker compose file because i made some changes, and the problem still persists.

This is the output of docker compose logs
https://pastebin.com/p3piwsii

Something is going wrong on the communication between seafile server and mariadb.

How to reproduce:
Download [docker compose file](https://github.com/ggogel/seafile-containerized/blob/master/compose/docker-compose.yml) into empty folder 
run `docker compose up`
Seafile fails to start.

**Comment by ggogel-exxeta** [comment]
I just made a fresh deployment on my local machine to verify this and I can't reproduce this.

Looking at your logs, it can connect to the database but the password of the `seafile` user isn't correct.

Are you sure you are starting from scratch? There might be volumes with existing config.

**Comment by ggogel** [comment]
I just made a fresh deployment on my local machine to verify this and I can't reproduce this.

Looking at your logs, it can connect to the database but the password of the `seafile` user isn't correct.

Are you sure you are starting from scratch? There might be volumes with existing config.

**Comment by ggogel** [comment]
Turns out I wasn't testing on a clean environment because Rancher Desktop doesn't clean up volumes properly.

The image for `seafile-server` was missing some scripts required for database initialization.

I just created a new release for `seafile-server`, which should fix the issue.

**Comment by Laikar** [comment]
Thanks for fixing the issue.
Also thanks for developing this project, it has saved me many hours of bashing my head against the official seafile containers.
Have a nice day.
