### ISSUE TITLE
Using Seafile-server without Seahub?

### ISSUE THREAD

**Issue by uuzp** [ggogel/seafile-containerized#289]
The issue arose when I noticed that the Seahub deployed on my VPS was consuming a significant amount of memory (600M+). 

Considering that I only use the client and do not require web services, would it be possible to proxy the requests for Seahub to the Seafile-server instead?

Specifically, should I forward port 8080 to 8082, 8083, and 8001?

 I am not entirely certain. 

Thank you for your assistance, and please provide any other potentially helpful suggestions.

**Comment by ggogel** [comment]
It should be possible to run it without seahub and only access the backend via webdav or the Seafile desktop clients. You might need seahub for initialization though.

**Comment by uuzp** [comment]
> It should be possible to run it without seahub and only access the backend via webdav or the Seafile desktop clients. You might need seahub for initialization though.

Thank you for your response.

I think if the time cost is only for running once (perhaps running it each time there is an update?), then it is somewhat acceptable. 

The main issue is that my VPS only has 768MB of memory, so I have to be very careful with resource allocation :)

From my initial assessment by reading the official documentation and Dockerfile, I believe seafile-server port 8082 is responsible for the main work, so is it changing from 8000 to 8082(seahub => seafile-server)?

Additionally, I noticed the seahub-media container simply copies static files into the container and then starts a web service to share these contents with seahub. Can I run the container once, mount these contents to an external volume, and then use an external proxy to directly share the contents with seahub?

Once again, thank you for your outstanding work. The modular containers have finally freed me from the complexity of the official container structure, allowing me to delve into more nuanced configuration work.

I will attempt this over the weekend and wish myself good luck. ^^
