### ISSUE TITLE
SEAFILE_SERVER_LETSENCRYPT variable

### ISSUE THREAD

**Issue by dimejo** [ggogel/seafile-containerized#30]
To me it looks like the `SEAFILE_SERVER_LETSENCRYPT` variable in `docker-compose.yml` is a leftover from the orignal Seafile configuration but no longer used in this project. Is that correct?

**Comment by ggogel** [comment]
Thank you. I had replaced it with the `HTTPS` variable at some point but forgot to remove the old one from the `docker-compose.yml`.
