### ISSUE TITLE
CSRF error on hub - new install

### ISSUE THREAD

**Issue by PierreRust** [ggogel/seafile-containerized#311]
I have an issue that is very similar to #138 , but on a completely new install, so I've created a new issue (of course, I can report in the original issue if you prefer).

I'm intend to run seafile behind a proxy (traekik, which handle certificates and dns).
I've followed the readme eand edited my compose file to set my url : 
```yaml
      - HTTPS=true
      - SEAFILE_URL=files.<mydomain>.net 
```

When logging in I get the following error on the Hub ui : "CSRF verification failed. Request aborted."

Looking at the logs, I find : 
```
seahub-1          | 2024-09-28 20:02:19,965 [WARNING] django.security.csrf:241 log_response Forbidden (Origin checking failed - https://files.<mydomain>.net does not match any trusted origins.): /accounts/login/

```

I've also checked the header in the login POST request : 
```
Request Header : 
Origin: https://files.<mydomain>.net
Referer: https://files.<mydomain>.net/accounts/login/?next=/
```
I suppose the issue is not on the proxy side then (as origin seems to be set correctly).

I'll try the workaround mentioned in #138  ( setting CSRF_TRUSTED_ORIGINS) but i's quite inconvenient as it requires editing the image.
Maybe this setting is now required and should be set automatically during installation ?

**Comment by ggogel** [comment]
Hi, please check if both URL in your Seafile admin settings use HTTPS as protocol.

**Comment by PierreRust** [comment]
Thanks for you're answer, but unfortunately I cannot get to the admin, as I cannot even log in :(

**Comment by PierreRust** [comment]
Quick update : I've added the CSRF_TRUSTED_ORIGINS settings and it worked, I could log in. I've checked the admin and both url use https.
Then I reverted back to the unmodified docker image for the hub and it still works, so I guess the change has somehow been persisted to the database.

Short story, my install now works ( still have to check uploads, sync, etc.)  but there still to be some issue in the initial setup process. Let me know if there is anything I could do to hep fixing this.  I don't know enough about Seafile internals to investigate by myself but should be able to help if you point me to the right direction.

**Comment by g1-infosec** [comment]
> Quick update : I've added the CSRF_TRUSTED_ORIGINS settings and it worked, I could log in. I've checked the admin and both url use https. Then I reverted back to the unmodified docker image for the hub and it still works, so I guess the change has somehow been persisted to the database.
> 
> Short story, my install now works ( still have to check uploads, sync, etc.) but there still to be some issue in the initial setup process. Let me know if there is anything I could do to hep fixing this. I don't know enough about Seafile internals to investigate by myself but should be able to help if you point me to the right direction.

Hi Pierre, where did you make this change?

In the official docker image, after install, the change needs to be made on this file: `/opt/seafile/seafile-server-latest/seahub/thirdpart/django/conf/global_settings.py` . Here one can specify the CSRF_TRUSTED_ORIGINS

But when I install using this docker image, that directory isn't there, so I can't seem to make the change after install. Did you modify the image prior to installing?

@ggogel As of v11, an updated version of Django will check for CSRF_TRUSTED_ORIGINS as an enhanced CSRF protection. Is there a way to map the value specified on the environment variable SEAFILE_URL to CSRF_TRUSTED_ORIGINS during deployment?

**Comment by PierreRust** [comment]
Actually I do not modify the image, I simply mount the `/shared` folder in a local directory and simply edit the config file in that directory.

For example in my compose file: 
 ```yaml
services:
  seafile-server:
    image: ggogel/seafile-server:11.0.12
    volumes:
       - ./data:/shared
    environment:
   [...]
```

in the mounter `./data` directory, I've  added the CSRF_TRUSTED_ORIGINS in `data/seafile/conf/seahub_settings.py`.

BTW I also found this to be  the easiest solution to configure JWT, and other options for onlyoffice integration.

**Comment by PierreRust** [comment]
I'm pretty sure the url are ok, but would not be so sure about the headers (I'm using traefik). I'm checked but as I don't really which headers are expected I might have missed something.

**Comment by ggogel** [comment]
For example `X-Forwarded-Proto` should be `https` and not `http`, as described in #138.

**Comment by ggogel** [comment]
After taking some time to investigate this issue, I was surprised to find that I could reproduce it in a new environment. When this problem first appeared in issue #138, I wasn't able to replicate it. Furthermore, in my long-running production environment, CSRF verification does not fail even without CSRF_TRUSTED_ORIGINS being set.

This inconsistency might be related to changes in the Seafile codebase, but I'm not certain and prefer not to delve deeper into it at this point. To mitigate the issue, I've implemented a startup function that checks if CSRF_TRUSTED_ORIGINS is already configured. If it is, the function does nothing. If it's not, the function sets CSRF_TRUSTED_ORIGINS to the value of SERVICE_URL.

Thanks for bringing the issue to my attention.

**Comment by PierreRust** [comment]
Great, thanks for your dedication !
