### ISSUE TITLE
Renew a certificat

### ISSUE THREAD

**Issue by Iwios** [ggogel/seafile-containerized#34]
Hi,

Can I have some help, my lets'encrypt cert was expired and I have some diffculties to renew cert.
It's another people mount this stack and I have no document to help my self.

Thank you

**Comment by ggogel** [comment]
Hi,

Let's encrypt is not part of this stack. I'm not sure how I should help you, especially with no info on how let's encrypt is implemented on your setup.

**Comment by Iwios** [comment]
Yes , I have generate my New certs.
After that any opérations was needed to re-imports certs?

I'm not very familiar with Docker :/

**Comment by ggogel** [comment]
Sorry, but again this project has nothing to do with let's encrypt. All common reverse proxies reissue let's encrypt certs automatically. I have still no idea what reverse proxy you are using, how you generated the new certs and where you want to import them.
