### ISSUE TITLE
[Question] Docker Volumes

### ISSUE THREAD

**Issue by alexw1982** [ggogel/seafile-containerized#5]
First of all: Thank you!

You write in your documentation "Of course you could also just use the old paths but I would strongly advise against that."

If I am running host mounts to a ZFS filesystem, what are in your opinion the disadvantages over docker volumes on a small deployment?

**Comment by ggogel** [comment]
The advantages of volumes are better managebility and in some cases better performance. You have all your persistent storage in one place and can manage it through docker.

I see that many users want to have their data on another volume. In this case there are two easy solutions. Either create a symlink to that path or use a storage plugin. What's the better option really depends on your storage setup. I'd say in your case the symlink is the better option. This is also described in the documentation.

**Comment by alexw1982** [comment]
Thanks! So far I am only running host mounts. I also thought about symlinking from the docker volumes storage - I simply like to have all my docker config files and data easily accessible and editable in one place on the host system (force of habit ;-) ). I know it is not ideal 

I also saw in the docker file that pyjwt is included: again, thank you! I've been waiting for the seafile guys to include that in their docker for some time now but lost hope in the end :-)

I really hope your work is going to make it upstream to become the official deployment method :-)
