### ISSUE TITLE
seafile-server did not start: fix_gunicorn_bind() function missing

### ISSUE THREAD

**Issue by hnz101** [ggogel/seafile-containerized#7]
Hi,

I don't know if this function is missing because I deployed 8.0.4 with your scripts or if it is a bug.
seafile wouldn't start properly because he couldn't find this function:

https://github.com/ggogel/seafile-containerized/blob/4bd4b8f24cd20e70dc6db29455378c8eae64902a/seafile-server/scripts/start.py#L55

removed this line and everything worked as expected.

**Comment by ggogel** [comment]
Hey,

thanks for the issue report. I forgot to remove this function call when I moved function to seahub. I wonder why this wasn't causing issues earlier to be honest.

I totally missed the release of 8.0.4. I'll release the images shortly.
