### ISSUE TITLE
Support initializing mysql database over IPv6

### ISSUE THREAD

**Issue by doppeleins** [ggogel/seafile-containerized#76]
Please add support for initializing the mysql database over IPv6.
Currently the mysql user is created with host `%.%.%.%` instead of `%`.

The change should be as simple as changing line 59 in seafile-server/scripts/bootstrap.py.

**Comment by ggogel** [comment]
The original file also has `%.%.%.%`, see https://github.com/haiwen/seafile-docker/blob/master/scripts_9.0/bootstrap.py

I'm not sure if changing it to `%` will break the validation in `setup-seafile-mysql.py`
