### ISSUE TITLE
Support for Seafile Professional Edition

### ISSUE THREAD

**Issue by bs10081** [ggogel/seafile-containerized#80]

**Comment by tschoesi** [comment]
I'm also interested in this. 
Currently using the pro version official dockerized setup, but there is some stuff there that I obviously don't like.

Is there anything holding us back from also using this for the pro version?
Would you accept a PR if I adapted this for the pro-version?

**Comment by ggogel** [comment]
I definitely will accept a PR about it.

About offering built container images I would need to double check the license agreement of the pro version but I think that it will likely violate it.

So probably I would just share the Dockefiles and scripts here such that people who are interested can built in themselves.

**Comment by zmmfa** [comment]
What would be required to run the pro version with "seafile-containerized" ? Currently, we are using the official pro image, but it has a lot of vulnerabilities.

**Comment by ggogel** [comment]
```
RUN cd /tmp && \
    wget https://download.seadrive.org/seafile-server_${SEAFILE_VERSION}_x86-64.tar.gz && \
    tar -zxvf seafile-server_${SEAFILE_VERSION}_x86-64.tar.gz && \
    rm -f seafile-server_${SEAFILE_VERSION}_x86-64.tar.gz
```

Here in the Dockerfile, you would need to download and extract the seafile-pro archive for `seafile-server`, `seahub` and `seahub-media`.

Then `seafile-server` and `seahub` might also require additional dependencies, i.e. Python modules.

**Comment by zmmfa** [comment]
Thanks, I'll try this in dev environment and see how it goes.

**Comment by simonhammes** [comment]
Hey,
I'm hoping this is not perceived as spam :)
We at datamate (the primary support and sales partner of Seafile in Europe) have developed a new Docker-based deployment approach for Seafile Professional Edition.

You can find all the relevant details here: https://forum.seafile.com/t/new-seafile-deployment-and-configuration-feedback-required/22305

We would be very grateful for your feedback (preferably as comments on the forum post)!

Thanks!
