### ISSUE TITLE
Is it a best practice to `docker compose exec seafile-server bash ` to the container to enable sefdav?

### ISSUE THREAD

**Issue by wangzexi** [ggogel/seafile-containerized#95]
Because it looks like `ggogel/seafile-server:10.0.1` does not have sefdav enabled by default.

```
# /opt/seafile/conf/seafdav.conf

[WEBDAV]
# Default is false. Change it to true to enable SeafDAV server.
enabled = true
port = 8080
share_name = /seafdav
```

Maybe we can enable SeafDAV by default here?
https://github.com/ggogel/seafile-containerized/blob/592645e028221ff506cf60fabc679085cc1e291c/seafile-server/scripts/bootstrap.py#L141-L151

**Comment by ggogel** [comment]
I don't see the need of enabling seafdav by default.

You can either use `docker exec` or manipulate the file directly from the host.
